### PR TITLE
Major refactoring

### PR DESCRIPTION
**Pull request by michalk8**
Hi @deeenes ,
sorry for not making the list last time, I was a bit busy. I've refactored most of the code to be more robust/extensible. Here's a highlight what's been done so far:
- fetching available query parameters from `/queries/<QUERY>` (I default to some pre-defined stuff if access to server can't be astablished)
- previously, the classes needed to be instantiated, now you can do things like `omnipath.interactions.Dorothea.get(...)`
- get available parameters for the query: `omnipath.interactions.Dorothea.params()`
- most of the packing stuff is done (i.e. pre-commits, docs*), except for CI
- automatically convert dtypes (can be disabled in options)
- logging

And what needs to be done:
- more logging
- add some nice text to the docs (I've converted the README from .md to .rST to that might be a good basis).
- the progress bar is still somewhat broken
- graph related stuff (what to use: networkx or igraph?) - I'd make this an optional dependency to make this as lightweight as possible
- **tests** (haven't done any) - will need to mock the connection to the server

I expect to be there many bugs, but I can start writing tests earliest this weekend.

* I've went ahead and tested whether I can build the docs under my account and can confirm that I was succesful:
https://omnipath.readthedocs.io/en/latest/api.html

### CODE REVIEW

**Comment by michalk8** [comment]
One point I forgot: it would be super cool that if in the future, https://omnipathdb.org/queries would also return `explanation` column or similar (in addition to argument and values) which could act as a docstring (I've made it so that it should be relatively easy to create the function docstrings of `get` method - currently the user only sees the correct function signature and it's a bit hacky, since it's not seen in the docs, because of how the docs are build).

**Comment by deeenes** [comment]
Hi @michalk8 ,

I just checked it out with your recent commits. It is fantastic, thank you for your great work! I really like the nice API with the `params` and `get`. For me it was a bit confusing to have the `requests` and `interactions` modules, first I was looking for the interaction queries inside the `requests` and then I realized I need to go one level up. Maybe for others it's more logical. 

More important, I get more or less different size data frames if I compare to the R package. I am wondering how I can check the logs to see the actual URLs, so I can look into it more in depth.

Until then I will merge this.

Best,

Denes

**Comment by deeenes** [comment]
> One point I forgot: it would be super cool that if in the future, https://omnipathdb.org/queries would also return `explanation` column or similar (in addition to argument and values) which could act as a docstring (I've made it so that it should be relatively easy to create the function docstrings of `get` method - currently the user only sees the correct function signature and it's a bit hacky, since it's not seen in the docs, because of how the docs are build).

Good idea, I will add this hopefully soon!

**Comment by michalk8** [comment]
Hi @deeenes ,
thanks for merging this.
> More important, I get more or less different size data frames if I compare to the R package. I am wondering how I can check the logs to see the actual URLs, so I can look into it more in depth.
You can set the logging level as:
```python3
import logging
logging.getLogger().setLevel(logging.DEBUG)
```

This might be because I was defaulting to `academic` license if `None` was specified. It's fixed here https://github.com/michalk8/omnipath/commit/c50b39b681c2e6e61e8a3a2fd48fde672127ef7c and I will write port the tests in OmnipathR over the weekend and create a new PR.

> Good idea, I will add this hopefully soon!

Sounds great, just let me know when it's ready. It would be also nice to return `Content-Length` in the response headers, if it doesn't cause too much troubles (it's really a minor thing for the progress bar).

**Pull request merged**
